export { default as AudioEditor } from './components/AudioEditor.vue'
export { useAudioEditor } from './composables/useAudioEditor'
export { AudioProcessor, type FfmpegAssets } from './core/audioProcessor'
export { defaultFfmpegAssets } from './core/defaultFfmpegAssets'
export { EditHistory } from './core/history'
